### ISSUE TITLE
Add benchmark referenced in README

### ISSUE THREAD

**Issue by headius** [janlelis/sig#1]
We are trying to finish up JRuby 9000, and the performance numbers you have in the README don't reflect what we expect to see. Would it be possible for you to post or commit the benchmark you're using (at least the sig part of it) so we can investigate why it's so slow? The JRuby community would thank you :-)

**Comment by janlelis** [comment]
Hey @headius,
sorry for originally benchmarking on that very old version of jruby 9000. I ran it again using a recent version and updated the readme. The benchmark used is this one: https://github.com/janlelis/sig/blob/v1.0.1/Rakefile#L33-L148

**Comment by headius** [comment]
Ahh, I see the problem. Because the benchmark is being run by rake and consists entirely of blocks, none of it ever runs in our compiled/jitted mode. So these numbers are for JRuby's interpreter, the slowest mode of execution.

Here's my results running the benchmark as a standalone script, so it is jit-compiled immediately:

```
[] ~/projects/sig $ jruby -Ilib blah.rb
ruby version: 2.2.2
sig version: 1.0.1
contracts version: 0.9
Calculating -------------------------------------
                pure    94.685k i/100ms
                 sig     6.504k i/100ms
           contracts     3.232k i/100ms
-------------------------------------------------
                pure     11.980M (±14.5%) i/s -     58.042M
                 sig    128.785k (± 7.3%) i/s -    643.896k
           contracts     44.822k (± 5.7%) i/s -    226.240k

Comparison:
                pure: 11979763.8 i/s
                 sig:   128784.7 i/s - 93.02x slower
           contracts:    44821.8 i/s - 267.28x slower


[] ~/projects/sig $ jruby -Xcompile.invokedynamic=true -Ilib blah.rb
ruby version: 2.2.2
sig version: 1.0.1
contracts version: 0.9
Calculating -------------------------------------
                pure   108.891k i/100ms
                 sig    10.117k i/100ms
           contracts     2.414k i/100ms
-------------------------------------------------
                pure     47.823M (±21.2%) i/s -    222.029M
                 sig    186.953k (± 8.3%) i/s -    930.764k
           contracts     47.508k (± 7.2%) i/s -    236.572k

Comparison:
                pure: 47823423.3 i/s
                 sig:   186953.0 i/s - 255.80x slower
           contracts:    47508.4 i/s - 1006.63x slower
```

**Comment by headius** [comment]
FWIW, I found the reason why rbx's numbers don't make any sense: after a certain number of iterations, they stop calling the type-checker: https://github.com/rubinius/rubinius/issues/3381

I don't think it's possible to get accurate jitted results for rbx until this issue is fixed.

**Comment by headius** [comment]
@janlelis The issue causing Rubinius's numbers to be inaccurate has been fixed! The numbers look much more realistic now:

```
# JRuby head
Calculating -------------------------------------
                pure   262.511k i/100ms
                 sig    33.787k i/100ms
-------------------------------------------------
                pure     46.170M (±16.2%) i/s -    222.347M
                 sig    424.254k (± 5.6%) i/s -      2.129M

Comparison:
                pure: 46169751.8 i/s
                 sig:   424254.3 i/s - 108.83x slower

# Rubinius head
Calculating -------------------------------------
                pure   247.597k i/100ms
                 sig    12.283k i/100ms
-------------------------------------------------
                pure     24.259M (± 9.3%) i/s -    119.837M
                 sig    147.844k (± 5.4%) i/s -    749.263k

Comparison:
                pure: 24259447.8 i/s
                 sig:   147843.8 i/s - 164.09x slower
```

**Comment by headius** [comment]
Oh, MRI 2.2 results, so you can tell how things run on my machine:

```
MRI 2.2
Calculating -------------------------------------
                pure    86.631k i/100ms
                 sig    12.212k i/100ms
-------------------------------------------------
                pure      6.180M (± 7.9%) i/s -     30.667M
                 sig    167.854k (± 5.7%) i/s -    842.628k

Comparison:
                pure:  6179752.2 i/s
                 sig:   167853.5 i/s - 36.82x slower
```

Somewhat surprising that MRI is actually _faster_ at running sig than Rubinius.

**Comment by janlelis** [comment]
Fantastic! Thanks a lot for investigating! :boom:

I'll update the Benchmark results in the README

**Comment by janlelis** [comment]
@headius I updated the results from my machine: https://github.com/janlelis/sig/#benchmark-take-with-a-grain-of-salt

However, the jruby one looks more like yours without invokedynamic. I ran it (in a standalone file) with `-Xcompile.invokedynamic=true -Xjit.threshold=0`
Do you have an idea?
